#!/usr/bin/python

import sys
import gtk
from subprocess import check_call, Popen, CalledProcessError

def clipboard_updated(clipboard=None, event=None):
    Popen(command, shell=True)

command = " ".join(sys.argv[1:])

primary_selection = gtk.clipboard_get(gtk.gdk.SELECTION_PRIMARY)
primary_selection.connect("owner-change", clipboard_updated)

try:
    gtk.main()
except KeyboardInterrupt:
    pass
